version: '3.8'


networks:
  cafeteria:
    name: cafeteria
    driver: bridge

services:
  
  mariadb:
    container_name: mariadb_cafeteria
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    ports:
      - "4002:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      
    networks:
      cafeteria:
        aliases: 
          - mariadb_host

  phpmyadmin:
    container_name: phpmyadmin_cafeteria
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: always
    expose:
      - "4003"
    ports:
      - "4003:80"
    environment:
      - PMA_HOST=mariadb_host
      - PMA_PORT=3306 
    networks:
      cafeteria:
        aliases: 
          - phpmyadmin_host
  

volumes:
  mariadb: