version: '3.8'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
  
  mariadb:
    driver: local
  # vol-https-portal-certs:
  #   driver: local

networks:
  iot:
    name: iot_host
    driver: bridge

services:
  
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    ports:
      - "4000:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      
    networks:
      iot:
        aliases: 
          - mariadb_host

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: always
    expose:
      - "4001"
    ports:
      - "4001:80"
    environment:
      - PMA_HOST=mariadb_host
      - PMA_PORT=3306 
    networks:
      iot:
        aliases: 
          - phpmyadmin_host
  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.14
    depends_on:
      - mariadb
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8073:8083
      - 8074:8084
      - 8072:8082
      - 8071:8081
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    extra_hosts:
      - "localhost:10.192.65.11"
    environment:
      EMQX_NAME: iothost-org
      EMQX_HOST: 127.0.0.1
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxpass"
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_NOMATCH: "deny"

      EMQX_DASHBOARD__LISTENER__HTTPS: 18084
      EMQX_DASHBOARD__LISTENER__HTTPS__ACCEPTORS: 2
      EMQX_DASHBOARD__LISTENER__HTTPS__MAX_CLIENTS: 2
      EMQX_DASHBOARD__LISTENER__HTTPS__KEYFILE: "/etc/letsencrypt/live/localhost/privkey.pem"
      EMQX_DASHBOARD__LISTENER__HTTPS__CERTFILE: "/etc/letsencrypt/live/localhost/fullchain.pem"
      EMQX_DASHBOARD__LISTENER__HTTP__MAX_CLIENTS: 2
      EMQX_MANAGEMENT__LISTENER_HTTPS: 8081
      EMQX_MANAGEMENT__LISTENER_HTTPS__ACCEPTORS: 2
      EMQX_MANAGEMENT__LISTENER_HTTPS__MAX_CLIENTS: 2
      EMQX_MANAGEMENT__LISTENER_HTTPS__BACKLOG: 2
      EMQX_MANAGEMENT__LISTENER_HTTPS__SEND_TIMEOUT: "15s"
      EMQX_MANAGEMENT__LISTENER_HTTPS__SEND__TIMEOUT_CLOSE: "on"
      EMQX_MANAGEMENT__LISTENER_HTTPS__CERTFILE: "/etc/letsencrypt/live/localhost/fullchain.pem"
      EMQX_MANAGEMENT__LISTENER_HTTPS__KEYFILE: "/etc/letsencrypt/live/localhost/privkey.pem"
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__WS__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mysql"
    networks:
      iot:
        aliases:
          - emqx_host

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   volumes:
  #     - vol-https-portal-certs:/var/lib/certbot
  #     - ./data/https-portal:/var/www/https-portal
  #   environment:
  #     DOMAINS: 'localhost -> http://emqx:8084'
  #     STAGE: 'production'
  #     DEFAULT_EMAIL: 'your-email@example.com'
  #   networks:
  #     iot:
  #       aliases:
  #         - https_portal
